### ISSUE TITLE
Weird auth issue with locally installed package

### ISSUE THREAD

**Issue by kof** [voronianski/node-tweet-cli#15]
When package is installed locally from cloned master:

```
➜  node-tweet-cli git:(master) ✗ sudo ./bin/tweet.js login
info:    Start sending request to https://twitter.com
https://api.twitter.com/oauth/request_token {}
{ statusCode: 400,
  data: '{"errors":[{"code":215,"message":"Bad Authentication data."}]}' }
error:   Error while executing command!
```

When same version 0.1.3 is installed via npm globally, it works. Very strange.

**Comment by voronianski** [comment]
The problem is that `.config.json` is only present only with npm package - https://github.com/voronianski/node-tweet-cli/blob/master/src/cli.js#L15.

Create this file in root `node-tweet-cli` folder with such content:

```json
{
	"consumerKey": "YOUR TWITTER CONSUMER KEY",
	"consumerSecret": "YOUR TWITTER CONSUMER SECRET"
}
```

**Comment by kof** [comment]
Thanks, this is worth documenting ...

**Comment by voronianski** [comment]
@kof agree.
